steps:
  # build the container image  # build the container image
  - name: 'node'
    entrypoint: npm
    args: ['install']
  - name: 'node'
    env:
      - 'APP_ENV=${BRANCH_NAME}'
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'ENVIRONMENT=${_APP_ENV}'
      - 'VERSION=${_VERSION}'
      - 'POPUP_URL=${_POPUP_URL}'
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'dist/cp.js', 'gs://${_PROJECT_ID}-loginbutton/${_APP_NAME}-${_APP_ENV}-${_APP_VERSION}.js']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'public/button.css', 'gs://${_PROJECT_ID}-loginbutton/${_APP_NAME}-${_APP_ENV}-${_APP_VERSION}.css']
